export enum PurchaseStatus {
    
    CREATED="CREATED",
    MODIFIED="MODIFIED",
    PENDING_APPROVAL="PENDING_APPROVAL",
    APPROVED="APPROVED",
    IN_PROCESS="IN_PROCESS",
    PROCESSED="PROCESSED",
    REJECTED="REJECTED",
    CANCELED="CANCELED"
}